#!/usr/bin/env python3
"""docs/pages/*.html をスキャンして docs/index.html (日付別リンク一覧) を生成"""
import re
from pathlib import Path
from datetime import datetime

REPO = Path(__file__).resolve().parent.parent
PAGES_DIR = REPO / "docs" / "pages"
INDEX_HTML = REPO / "docs" / "index.html"


def collect_pages() -> list[dict]:
    """日付htmlファイルを収集し、タイトルを抽出"""
    pages = []
    for f in sorted(PAGES_DIR.glob("*.html"), reverse=True):
        date_str = f.stem  # e.g. "2026-06-13"
        # タイトル抽出
        try:
            text = f.read_text(encoding="utf-8")
            m = re.search(r"<title>(.+?)</title>", text)
            title = m.group(1) if m else date_str
        except Exception:
            title = date_str
        pages.append({
            "date": date_str,
            "title": title,
            "filename": f.name,
        })
    return pages


def build_index(pages: list[dict]) -> str:
    rows = ""
    for p in pages:
        rows += (
            f'<tr>'
            f'<td class="date">{p["date"]}</td>'
            f'<td class="title-col">'
            f'<a href="pages/{p["filename"]}">{p["title"]}</a>'
            f'</td>'
            f'</tr>\n'
        )

    return f"""<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>📰 claude-news アーカイブ</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    background: #f5f5f5; color: #333; line-height: 1.6;
  }}
  .container {{ max-width: 640px; margin: 0 auto; padding: 32px 16px; }}
  h1 {{ font-size: 1.5rem; text-align: center; padding: 16px 0 24px; color: #1a1a2e; }}
  .count {{ text-align: center; color: #888; font-size: .9rem; margin-bottom: 24px; }}
  table {{ width: 100%; border-collapse: collapse; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,.08); }}
  td {{ padding: 12px 16px; border-bottom: 1px solid #eee; }}
  tr:last-child td {{ border-bottom: none; }}
  .date {{ width: 120px; color: #999; font-size: .9rem; font-family: monospace; white-space: nowrap; }}
  .title-col a {{ color: #2a4f85; text-decoration: none; font-weight: 500; }}
  .title-col a:hover {{ text-decoration: underline; }}
  footer {{ text-align: center; padding: 32px 0; font-size: .78rem; color: #999; }}
  footer a {{ color: #666; text-decoration: none; }}
</style>
</head>
<body>
<div class="container">
<h1>📰 claude-news アーカイブ</h1>
<p class="count">{len(pages)} 件のニュース要約</p>
<table>
{rows}
</table>
<footer>
  Generated by <a href="https://github.com/lighter265/claude-news">claude-news</a>
  · {datetime.now().strftime("%Y-%m-%d %H:%M JST")}
</footer>
</div>
</body>
</html>"""


def main():
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    pages = collect_pages()
    html = build_index(pages)
    INDEX_HTML.write_text(html, encoding="utf-8")
    print(f"Generated {INDEX_HTML} ({len(pages)} pages, {len(html)} bytes)")


if __name__ == "__main__":
    main()
